blank_issues_enabled: false
contact_links:
    -   name: Support Questions & Other
        url: https://github.com/orgs/cashbox-laravel/discussions
        about: Discuss any issues related to the application or templates working with it.
