name: Code Style

on: [ push, pull_request ]

permissions: write-all

jobs:
    style:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Detect job name
                id: detect
                run: |
                    [[ ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} ]] && NAME="Fix" || NAME="Check"

                    echo "name=${NAME}" >> $GITHUB_OUTPUT

            -   name: ${{ steps.detect.outputs.name }} the code style
                uses: TheDragonCode/codestyler@v3
                with:
                    github_token: ${{ secrets.COMPOSER_TOKEN }}
                    fix: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    normalize:
        needs: style
        
        runs-on: ubuntu-latest
        
        strategy:
            fail-fast: true
            matrix:
                file:
                    - src/Core
                    - src/Cash
                    - src/SberAuth
                    - src/SberOnline
                    - src/SberQrCode
                    - src/TinkoffAuth
                    - src/TinkoffCredit
                    - src/TinkoffOnline
                    - src/TinkoffQrCode
                    - src/TemplateDriver
                    - src/TemplateDriverAuth
        
        if: ${{ github.event_name == 'push' && contains(fromJSON('["refs/heads/main", "refs/heads/4.x"]'), github.ref) }}
        
        steps:
            -   name: Install dependency
                run: composer global require ergebnis/composer-normalize

            -   name: Normalize composer.json
                run: |
                    composer normalize ${{ matrix.file }}/composer.json

            -   name: Create a Pull Request
                uses: peter-evans/create-pull-request@v4
                with:
                    branch: projects/patch
                    branch-suffix: random
                    delete-branch: true
                    add-paths: .
                    title: "Normalized `composer.json` files"
                    commit-message: Normalized `composer.json` files
                    body: Normalized `composer.json` files
