name: Databases

on: [ push, pull_request ]

jobs:
    mysql:
        runs-on: ubuntu-latest
        
        strategy:
            fail-fast: true
            matrix:
                db: [ "5.7", "8" ]
        
        name: MySQL ${{ matrix.db }}
        
        services:
            mysql:
                image: mysql:${{ matrix.db }}
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: forge
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql, json
                    coverage: none

            -   name: Install dependencies
                uses: nick-fields/retry@v2
                with:
                    timeout_minutes: 5
                    max_attempts: 5
                    command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress --optimize-autoloader

            -   name: Execute tests
                run: vendor/bin/pest  --colors=always
                env:
                    DB_CONNECTION: mysql
                    DB_USERNAME: root
    
    mariadb:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                db: [ "10" ]

        name: MariaDB ${{ matrix.db }}

        services:
            mysql:
                image: mariadb:${{ matrix.db }}
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: forge
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql, json
                    coverage: none

            -   name: Install dependencies
                uses: nick-fields/retry@v2
                with:
                    timeout_minutes: 5
                    max_attempts: 5
                    command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress --optimize-autoloader

            -   name: Execute tests
                run: vendor/bin/pest  --colors=always
                env:
                    DB_CONNECTION: mysql
                    DB_USERNAME: root
    
    pgsql:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                db: [ "14", "15" ]

        name: PostgreSQL ${{ matrix.db }}

        services:
            postgresql:
                image: postgres:${{ matrix.db }}
                env:
                    POSTGRES_DB: forge
                    POSTGRES_USER: forge
                    POSTGRES_PASSWORD: password
                ports:
                    - 5432:5432
                options: --health-cmd=pg_isready --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_pgsql, json
                    coverage: none

            -   name: Install dependencies
                uses: nick-fields/retry@v2
                with:
                    timeout_minutes: 5
                    max_attempts: 5
                    command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress --optimize-autoloader

            -   name: Execute tests
                run: vendor/bin/pest  --colors=always
                env:
                    DB_CONNECTION: pgsql
                    DB_PASSWORD: password
    
    mssql:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                db: [ "2019", "2022" ]

        name: SQL Server ${{ matrix.db }}

        services:
            sqlsrv:
                image: mcr.microsoft.com/mssql/server:${{ matrix.db }}-latest
                env:
                    ACCEPT_EULA: Y
                    SA_PASSWORD: Forge123
                ports:
                    - 1433:1433

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_sqlsrv, json, odbc, pdo_odbc
                    coverage: none

            -   name: Install dependencies
                uses: nick-fields/retry@v2
                with:
                    timeout_minutes: 5
                    max_attempts: 5
                    command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress --optimize-autoloader

            -   name: Execute tests
                run: vendor/bin/pest  --colors=always
                env:
                    DB_CONNECTION: sqlsrv
                    DB_DATABASE: master
                    DB_USERNAME: SA
                    DB_PASSWORD: Forge123
