name: Release

on:
    create:
        tags:
            - v4.*
    
    delete:
        tags:
            - *
    
    workflow_dispatch:
        inputs:
            tag:
                description: 'Tag version'
                required: true
                options:
                    - v4

jobs:
    deploy:
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Resolve version
                id: tag
                run: |
                    if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
                      GITHUB_REF=${{ github.event.inputs.tag }}
                    else
                      GITHUB_REF=${{ github.ref_name }}
                    fi          
                    echo "tag=${GITHUB_REF##*v}" >> "$GITHUB_OUTPUT"

            -   name: Components release
                run: ./bin/release.sh ${{ steps.tag.outputs.tag }}
