name: Release

on:
    release:
        types:
            - released
        tags:
            - v4.*
    
    workflow_dispatch:
        inputs:
            tag:
                description: 'Tag version'
                required: true
                options:
                    - v4

jobs:
    configure:
        runs-on: ubuntu-latest
        
        name: Configure
        
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
            tag: ${{ steps.ids.outputs.tag }}
        
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup GIT
                uses: frankdejonge/use-github-token@1.0.1
                with:
                    authentication: '${{ secrets.COMPOSER_USERNAME }}:${{ secrets.COMPOSER_TOKEN }}'
                    user_name: 'Andrey Helldar'
                    user_email: 'helldar@dragon-code.pro'

            -   name: Set matrix data
                id: set-matrix
                run: echo "matrix=$(jq -c . < ./split.json)" >> $GITHUB_OUTPUT

            -   name: Get version
                id: ids
                run: |
                    TAG=${{ github.event.release.tag_name || github.event.inputs.tag }}
                    
                    echo "tag=v${TAG##*v}" >> "$GITHUB_OUTPUT"
    
    release:
        runs-on: ubuntu-latest
        needs: configure
        
        strategy:
            matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
        
        name: ${{ matrix.sub-splits.name }}
        
        if: ${{ contains(toJson(matrix.sub-splits), '.release') && matrix.sub-splits.release != false }}
        
        steps:
            -   name: Show version
                run: echo "${{ needs.configure.outputs.tag }}"

            -   name: Component release
                run: |
                    echo "${{ matrix.sub-splits.name }}"
                    echo "${{ matrix.sub-splits.target }}"
            #                run: ./bin/release.sh ${{ steps.ids.outputs.tag }}
