name: Split

on:
    push:
        branches:
            - main
            - 4.x
    workflow_dispatch:

jobs:
    components:
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
                with:
                    fetch-depth: '0'
                    persist-credentials: 'false'

            -   name: Extract branch name
                id: extract_branch
                run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

            -   name: Setup GIT
                uses: frankdejonge/use-github-token@1.0.2
                with:
                    authentication: '${{ secrets.COMPOSER_USERNAME }}:${{ secrets.COMPOSER_TOKEN }}'
                    user_name: 'GitHub Action'
                    user_email: 'action@github.com'

            -   name: Cache splitsh-lite
                id: splitsh-cache
                uses: actions/cache@v3
                with:
                    path: './.splitsh'
                    key: '${{ runner.os }}-splitsh-d-101'

            -   name: Extract components
                uses: frankdejonge/use-subsplit-publish@1.0.0-beta.7
                with:
                    source-branch: ${{ steps.extract_branch.outputs.branch }}
                    splitsh-path: './.splitsh/splitsh-lite'
                    config-path: split.json
