name: Split

on:
    push:
        branches:
            - main
            - 4.x
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, bcmath
                    coverage: none

            -   name: Components release
                run: sudo ./bin/split.sh
