name: Tests

on: [ push, pull_request ]

jobs:
    linux:
        runs-on: ubuntu-latest
        
        strategy:
            fail-fast: true
            matrix:
                php: [ "8.1", "8.2", "8.3" ]
                stability: [ "prefer-lowest", "prefer-stable" ]
        
        name: PHP ${{ matrix.php }} - ${{ matrix.stability }}
        
        services:
            mysql:
                image: mysql:8
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: forge
                ports:
                    - 33306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
            redis:
                image: redis:latest
                ports:
                    - 6379:6379
                options: --entrypoint redis-server

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, pdo_mysql, gd, redis-phpredis/phpredis@5.3.7, igbinary, msgpack, lzf, zstd, lz4, gmp
                    ini-values: error_reporting=E_ALL
                    coverage: none
                env:
                    REDIS_CONFIGURE_OPTS: --enable-redis --enable-redis-igbinary --enable-redis-msgpack --enable-redis-lzf --with-liblzf --enable-redis-zstd --with-libzstd --enable-redis-lz4 --with-liblz4
                    REDIS_LIBS: liblz4-dev, liblzf-dev, libzstd-dev

            -   name: Install dependencies
                uses: nick-fields/retry@v2
                with:
                    timeout_minutes: 5
                    max_attempts: 5
                    command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress --optimize-autoloader

            -   name: Execute tests
                run: vendor/bin/pest --parallel --colors=always
                env:
                    DB_CONNECTION: mysql
                    DB_USERNAME: root
                    DB_PORT: ${{ job.services.mysql.ports[3306] }}
    
    windows:
        runs-on: windows-latest
        
        strategy:
            fail-fast: true
            matrix:
                php: [ "8.1", "8.2", "8.3" ]
                stability: [ "prefer-lowest", "prefer-stable" ]
        
        name: PHP ${{ matrix.php }} - ${{ matrix.stability }} - Windows
        
        services:
            mysql:
                image: mysql:8
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: forge
                ports:
                    - 33306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
            redis:
                image: redis:latest
                ports:
                    - 6379:6379
                options: --entrypoint redis-server

        steps:
            -   name: Set git to use LF
                run: |
                    git config --global core.autocrlf false
                    git config --global core.eol lf

            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, pdo_mysql, gd, redis-phpredis/phpredis@5.3.7, igbinary, msgpack, lzf, zstd, lz4, gmp
                    ini-values: error_reporting=E_ALL
                    coverage: none
                env:
                    REDIS_CONFIGURE_OPTS: --enable-redis --enable-redis-igbinary --enable-redis-msgpack --enable-redis-lzf --with-liblzf --enable-redis-zstd --with-libzstd --enable-redis-lz4 --with-liblz4
                    REDIS_LIBS: liblz4-dev, liblzf-dev, libzstd-dev

            -   name: Install dependencies
                uses: nick-fields/retry@v2
                with:
                    timeout_minutes: 5
                    max_attempts: 5
                    command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress --optimize-autoloader

            -   name: Execute tests
                run: vendor/bin/pest --parallel --colors=always
                env:
                    DB_CONNECTION: mysql
                    DB_USERNAME: root
                    DB_PORT: ${{ job.services.mysql.ports[3306] }}
