name: tmp

on:
    push:

jobs:
    release:
        runs-on: ubuntu-latest
        
        strategy:
            fail-fast: true
            matrix:
                package:
                    - { "name": "Foo", "release": false }
                    - { "name": "Bar" }
        
        name: ${{ matrix.package.name }}
        
        if: ${{ contains(matrix.package, 'release') }}
        
        steps:
            -   name: Show info
                run: echo "${{ toJson(matrix) }}"
